name: MiniGameAPI
version: ${project.version}
main: nl.bramkoene.knockarena.KnockArena
api-version: 1.13
authors: [Minestarnl]
description: A minecraft knockback arena minigame
website: bramkoene.nl
commands:
  setarenaspawnpoint:
    description: Sets an arena spawn point
    usage: /setarenaspawnpoint
    aliases:
      - sasp
    permission: KnockArena.Builder
  setlobbyspawnpoint:
    description: Sets an lobby spawn point
    usage: /setlobbyspawnpoint
    aliases:
      - slsp
    permission: KnockArena.Builder
  creategame:
    description: starts a game
    usage: /creategame
    aliases:
      - ska
    permission: KnockArena.Manager
  joingame:
    description: starts a game
    usage: /joingame
    aliases:
      - ska
    permission: KnockArena.Manager

permissions:
  KnockArena.Builder:
    description: Allows to make spawnpoints and build stuff
    default: true
  KnockArena.Manager:
    description: Allows to start/stop running games
    default: true
