name: MiniGameAPI
version: 1.0.0.2
main: nl.bramkoene.minigameapi.MiniGameAPI
api-version: 1.13
authors: [Minestarnl]
description: A minecraft knockback arena minigame
website: bramkoene.nl
commands:
  setarenaspawnpoint:
    description: Sets an arena spawn point
    usage: /setarenaspawnpoint
    aliases:
      - sasp
    permission: MiniGameApi.Builder
  setlobbyspawnpoint:
    description: Sets an lobby spawn point
    usage: /setlobbyspawnpoint
    aliases:
      - slsp
    permission: MiniGameApi.Builder
  creategame:
    description: starts a game
    usage: /creategame
    aliases:
      - ska
    permission: MiniGameApi.Manager
  joingame:
    description: starts a game
    usage: /joingame
    aliases:
      - ska
    permission: MiniGameApi.join
  buildminigame:
    description: Allows you to create the game. This should be done after any arena has been build
    usage: "Usage: /buildgame <gameType>"
    permission: MiniGameApi.Builder
  jointeam:
    description: joins a team
    usage: /jointeam <Player>
    aliases:
      - jt
    permission: MiniGameApi.Team
  getminigames:
    description: Shows all installed minigames
    usage: /getminigames
    permission: MiniGameApi.Info

permissions:
  MiniGameApi:
    Info: shows info of the api
    default: true
  MiniGameApi.Team:
    description: allows usage of teams
    default: true
  MiniGameApi.Builder:
    description: Allows to make spawnpoints and build stuff
    default: op
  MiniGameApi.Manager:
    description: Allows to start/stop running games
    default: op
  MiniGameApi.join:
    description: allows to join
    default: true
